### ISSUE TITLE
Want to add a new Open Source Event in the list

### ISSUE THREAD

**Issue by Soumyajit2825** [ayush-sleeping/All-the-Open-Source-Programs#6]
Event Name - Apertre - An Open Source Event
Organised By - [Resourcio Community](https://resourcio.tech/) and [GDSC AOT](https://gdsc.community.dev/academy-of-technology-hooghly/)
Event Website - https://os.apertre.tech/
Event Timeline - 3rd JAN 2024 - 17th JAN 2024
Description - "Apertre":  15-day tech program by Resourcio and Google Developer Students Club - Academy Of Technology. Enhance web, mobile, and ML skills, collaborate on real projects, mentorship. Open to all levels. Boost experience, portfolio, and tech career.

@ayush-sleeping

**Comment by ayush-sleeping** [comment]
> Event Name - Apertre - An Open Source Event Organised By - [Resourcio Community](https://resourcio.tech/) and [GDSC AOT](https://gdsc.community.dev/academy-of-technology-hooghly/) Event Website - https://os.apertre.tech/ Event Timeline - 3rd JAN 2024 - 17th JAN 2024 Description - "Apertre": 15-day tech program by Resourcio and Google Developer Students Club - Academy Of Technology. Enhance web, mobile, and ML skills, collaborate on real projects, mentorship. Open to all levels. Boost experience, portfolio, and tech career.
> 
> @ayush-sleeping


Hi @Soumyajit2825 , 

I hope this message finds you well. I noticed that you've created an issue in the repository, and I appreciate your engagement with the OS Programs list. I've reviewed the suggestions, and I agree that adding the following programs would be valuable.

If you could kindly create a PR with these additions, I'd be more than happy to review and merge it into the main branch.

**Comment by Soumyajit2825** [comment]
> > Event Name - Apertre - An Open Source Event Organised By - [Resourcio Community](https://resourcio.tech/) and [GDSC AOT](https://gdsc.community.dev/academy-of-technology-hooghly/) Event Website - https://os.apertre.tech/ Event Timeline - 3rd JAN 2024 - 17th JAN 2024 Description - "Apertre": 15-day tech program by Resourcio and Google Developer Students Club - Academy Of Technology. Enhance web, mobile, and ML skills, collaborate on real projects, mentorship. Open to all levels. Boost experience, portfolio, and tech career.
> > @ayush-sleeping
> 
> Hi @Soumyajit2825 ,
> 
> I hope this message finds you well. I noticed that you've created an issue in the repository, and I appreciate your engagement with the OS Programs list. I've reviewed the suggestions, and I agree that adding the following programs would be valuable.
> 
> If you could kindly create a PR with these additions, I'd be more than happy to review and merge it into the main branch.

Sure!
I am doing a PR!
Thanks
